### ISSUE TITLE
Existing drug terminologies and normalization services

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/therapy-normalization#1]
This thread tracks known and public drug terminologies and normalization services. Initial list here: https://docs.google.com/spreadsheets/d/1bhA4RVt7HT2oIMVWeaXcnxFNcUQ4rEl9mB5cBSK8Kzw/edit#gid=0

**Comment by jeremywarner** [comment]
Practicing writing a comment - next I'll figure out how to push the new rows I added (regimens)

**Comment by BalaguruRavikumar** [comment]
Anatomical Therapeutic Chemical Drug classification system.

**Comment by jeremywarner** [comment]
> Anatomical Therapeutic Chemical Drug classification system.

Yes - we have that one in the list of databases (ATC). Row 2 of the Google Doc. Please let us know if you see other missing terminologies!

**Comment by jeremywarner** [comment]
I found two additional terminologies while poking around today - DTP/NCI, and EPA DSSTox. I've added to my local database but might be better if I add the document to the Git repository? I also have a separate spreadsheet of web resources, which I distinguish from terminologies in that they don't maintain their own (externally available) code set to represent the concepts contained within.

**Comment by jsstevenson** [comment]
I'm calling this one "stale"
