### ISSUE TITLE
ChEMBL normalizer not matching case-sensitively

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#14]
The ChEMBL normalizer returns match_type code 100 (a case-sensitive primary match) for what should be case-insensitive primary matches, eg:

<img width="321" alt="Screen Shot 2020-10-01 at 12 06 26 PM" src="https://user-images.githubusercontent.com/12942397/94835090-35cab700-03df-11eb-960a-109d3d0c89e9.png">

...and the same for alias matches:

<img width="370" alt="Screen Shot 2020-10-01 at 12 07 00 PM" src="https://user-images.githubusercontent.com/12942397/94835167-4f6bfe80-03df-11eb-8fed-74176845ee9f.png">

**Comment by ahwagner** [comment]
Is this an issue on the `dgidb` branch? That branch is more developed, we will want to merge it into `master` (see #11) as one of our first steps.

**Comment by ahwagner** [comment]
This is present on `dgidb`.
