### ISSUE TITLE
Swap "xref" and "other_id" in DB/search endpoint

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#149]
To attain consistency with the Value Object Descriptor specs, we need to update schemas, search endpoint output, and database storage attributes so that references to included sources are "xrefs" and references to other sources are "other_identifiers".

**Comment by korikuzma** [comment]
Should we consider references to other sources as `associated_with`? https://github.com/cancervariants/therapy-normalization/blob/main/therapy/query.py#L398
