### ISSUE TITLE
Normalize DrugBank/other source concept IDs that omit namespaces

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#187]
Eg, for search term `DB04050`, since it can be matched against a simple regex we should be able to try it as `drugbank:DB04050` if it otherwise fails to normalize. This is something we already perform within the `search/` endpoint and may be relevant to other normalizers as well.

**Comment by korikuzma** [comment]
Good idea! We should include a warning that contains the query we tried and found a match for.

**Comment by jsstevenson** [comment]
I think this is a reasonable default, but given the warning, I wonder if we should provide an API option to override this? like `force_exact=true` means that there's no attempt to search with an inferred namespace.

**Comment by jsstevenson** [comment]
Resolved in #200
