### ISSUE TITLE
Add disease indications in ChEMBL

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#191]
ChEMBL appears to provide pretty rich drug indication data, including MeSH headings, EFO terms, and some associated IDs to try normalizing. We should add this to existing `fda_indication` data now that ChEMBL is being added to the `normalize/` endpoint.

**Comment by korikuzma** [comment]
This information is found in the `drug_indication` table

**Comment by jsstevenson** [comment]
Resolved in #245
