### ISSUE TITLE
Use latest versions of source data

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/therapy-normalization#204]
We always download version 27 for ChEMBL, but we should change this to using the latest version

**Comment by jsstevenson** [comment]
- [ ] Fetch latest wikidata
- [ ] Fetch latest ChEMBL
- [ ] Fetch latest RxNorm
- [ ] Fetch latest ChemIDPlus
- [ ] Fetch latest DrugBank

**Comment by jsstevenson** [comment]
Fixed in #210
