### ISSUE TITLE
Evaluate reasons for failure of drugs to normalize to concept

### ISSUE THREAD

**Issue by mcannon068nw** [cancervariants/therapy-normalization#205]
Trying to identify commonalities between drugs that failure to normalize to a concept (using DGIdb's current drug set as an input)

**Comment by mcannon068nw** [comment]
Fixing inferred namespace issue (i.e. drugbank:DB### vs DB#### as input) for normalize function will bring us up to 43504 normalized concepts (75.66%). This will put us past DGIdb's (v4.2.0) 39740 normalized concepts (69.11%).

Additionally, inclusion of a new source such as PubChem (if possible) will fix issues with GtP SIDs and US pIDs and put us up to 51045 normalized concepts (88.77%)

**Comment by mcannon068nw** [comment]
There are 300 biologics (CAR-T cell therapies, vaccines, etc) not normalizing. Looking into fix for this

Additionally, there are 2494 'analog' and 'derivative' inputs that are likely very hard to normalize (i.e: Maleimides derivative 2, Peptide analog 29). Some of these are findable in PubChem, but unsure how reliable that would be for these inputs.

**Comment by jsstevenson** [comment]
A few other associated issues:

#86 

#101 

#169

#204

**Comment by jsstevenson** [comment]
A few other possibly associated issues:

#86 

#101 

#169 

#204

**Comment by mcannon068nw** [comment]
Analysis done and change to address unnormalized concepts made in other PRs
