### ISSUE TITLE
ChEMBL not capturing trade names correctly 

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/therapy-normalization#213]
[CHEMBL40](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL40/) has trade names: `Eskabarb` ,`Luminal` ,`Noptil` ,`Phenobarbitone` ,`Solfoton` ,`Talpheno` . However, we are currently storing these as `aliases`. 

In `molecule_synonyms` we should also be checking for `syn_type=TRADE_NAME`.

**Comment by jsstevenson** [comment]
Resolved in #245
