### ISSUE TITLE
Add TQDM to things

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#312]
Use [manual](https://github.com/tqdm/tqdm#manual) control combined with known file sizes or [estimated table sizes](https://stackoverflow.com/a/42863034/7417073) where relevant

**Comment by korikuzma** [comment]
It might be nice to have this for the `_transform_data` method. I'm trying to run ETL methods as a ECS task, but NCIt seems to be hanging (using `thera-py[etl]==0.5.0.dev2`). After running throughout the night (12+ hours probably), last log I have is `Transforming and loading data to DB...`. It would be nice to have these logs in this case
