### ISSUE TITLE
Trade Name normalization

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/therapy-normalization#37]
DGIdb did not successfully identify ChEMBL concepts for several drug trade names:

- TECFIDERA
- ADRIAMYCIN
- WESTCORT
- CASODEX
- FOSCAVIR

We may not be searching those, let's be sure to add ChEMBL trade names to our search index.

**Comment by susannasiebert** [comment]
To clarify, these terms do return a ChEMBL results but only with a `match_type` of `60` which makes them rank lower than the wikidata results.
