### ISSUE TITLE
Wikidata normalizer update / retrieve methods

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/therapy-normalization#7]
Currently we focus only on _loading_ data for normalizers, but for this to be production ready / reusable we need to provide methods to update the data files used for the normalizers.

**Comment by ahwagner** [comment]
The ChEMBL normalizer has this built in now. However, the Wikidata SPARQL service does not have a parallel output for their http SPARQL API endpoint. They offer only the _verbose_ JSON instead, which is substantially larger and would require additional pre-processing.

**Comment by jsstevenson** [comment]
Closed in #85
