### ISSUE TITLE
Update other_identifiers and xrefs

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/therapy-normalization#76]
`other_identifiers` should now include RxNorm and ChemIDPlus.

**Comment by jsstevenson** [comment]
I think we are all caught up on this as of [this commit](https://github.com/cancervariants/therapy-normalization/commit/0b43a3e03638bdedda2aa672496f50f4639e27c8) but you should probably double-check me before this issue closes.

**Comment by korikuzma** [comment]
> I think we are all caught up on this as of [this commit](https://github.com/cancervariants/therapy-normalization/commit/0b43a3e03638bdedda2aa672496f50f4639e27c8) but you should probably double-check me before this issue closes.

Sorry, this issue was to update the production database but I believe that running [this](https://github.com/cancervariants/therapy-normalization/blob/main/dynamodb_revisions/add_xrefs.py) again will also work.
