### ISSUE TITLE
Background data loading

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/therapy-normalization#8]
Currently the application will silently load data for the normalizers in the background if missing on startup. Users are not notified, and may think application is hanging.

Possible solutions include:
1. A console handler for the logger, which can be used to emit loading messages to terminal as they are captured by the logger.
2. Raising an exception, with an alternate endpoint for preparing data.

**Comment by jsstevenson** [comment]
I'm satisfied with our current efforts for this, so I'm closing this ticket.
