### ISSUE TITLE
Add GSIs on record types

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/therapy-normalization#89]

**Comment by korikuzma** [comment]
I think we'd want to make add a new attribute like `label_type` to all the records, right?

**Comment by jsstevenson** [comment]
Yeah -- what's the use case for accessing just labels vs aliases? Would be able to speed up querying times by restricting filters to just record types?

**Comment by korikuzma** [comment]
It might be. If for some reason we do need access to certain label types, I think it'd be useful to have the `label_type` attribute. So I think it's best if we just store the type there rather than creating an attribute for what we need now (identity/merge).
